name: 'Example: Sticky Comment Body Path'

on:
  pull_request:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MeilCli/hidable-comment-action@v2
        with:
          number: ${{ github.event.pull_request.number }}
          show: true
          id: 'example-sticky-comment-body-path'
          body_path: '.github/workflows/example-sticky-comment-body-path.md'
