name: 'Example: Sticky Checklist comment'

on:
  pull_request:
jobs:
  example:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: MeilCli/hidable-comment-action@master
        with:
          number: ${{ github.event.pull_request.number }}
          show: true
          id: 'example-sticky-comment-checklist'
          body_path: '.github/workflows/example-sticky-comment-checklist.md'
