name: 'Example: Sticky Checklist comment'

on:
  pull_request:
jobs:
  example:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: MeilCli/hidable-comment-action@master
        with:
          number: ${{ github.event.pull_request.number }}
          show: true
          id: 'example-sticky-comment-checklist'
          body_path: '.github/workflows/example-sticky-comment-checklist.md'
