name: 'Example: Sticky Comment Body'

on:
  pull_request:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: MeilCli/hidable-comment-action@v2
        with:
          number: ${{ github.event.pull_request.number }}
          show: true
          id: 'example-sticky-comment-body'
          body: |
            Example sticky comment body
            - This action can upsert comment body
            - This action can set multiple sticky comment by id
